### ISSUE TITLE
zraxx - The function `redo` can be used to steal all funds in `vat`.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-makerdao-endgame-judging#29]
zraxx

High

# The function `redo` can be used to steal all funds in `vat`.

### Summary

The lack of permission check for the `redo` function in `LockstakeClipper.sol` will result in the function `redo` being called arbitrarily, thereby stealing incentive funds.

### Root Cause

https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/lockstake/src/LockstakeClipper.sol#L275-L313
Lack of permission check for the `redo` function.

### Internal pre-conditions

1. The auth user sets the chip or tip to larger than 0
2. The auth user first calls the function `kick` to start the auction.
3. Attackers calls the function `redo` repeatedly to steal the incentive funds.

### Attack Path

1. Attackers calls the function `redo` repeatedly to steal the incentive funds.

### Impact

All the funds in `vat` will be stolen by attackers.

### Mitigation

Add the `auth` check for the function `redo`.

**Comment by sunbreak1211** [comment]
There is a check if the auction needs a reset -https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/lockstake/src/LockstakeClipper.sol#L289
