### ISSUE TITLE
bareli - Max approvals to any address is possible

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-makerdao-endgame-judging#59]
bareli

Medium

# Max approvals to any address is possible

## Summary
Approve function  can be called by anyone to give max approval to
any address for any ERC20 token. Any ERC20 token left in the  can be stolen
## Vulnerability Detail
 function approve(address spender, uint256 value) external returns (bool) {
        allowance[msg.sender][spender] = value;

        emit Approval(msg.sender, spender, value);

        return true;
    }
## Impact
ERC20 token left in the  can be stolen
## Code Snippet
https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/ngt/src/Ngt.sol#L137C4-L143C6
## Tool used

Manual Review

## Recommendation
 function approve(address spender, uint256 value) external returns (bool)  auth{
        allowance[msg.sender][spender] = value;

        emit Approval(msg.sender, spender, value);

        return true;
    }

**Comment by telome** [comment]
As the code clearly shows, one can only change its own allowance.
