### ISSUE TITLE
zraxx - Function `deposit` and `mint` have no slippage protection.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-makerdao-endgame-judging#79]
zraxx

Medium

# Function `deposit` and `mint` have no slippage protection.

### Summary

The missing slippage protection  for `deposit` and `mint` in `SNst.sol` will cause user unexpected deposit and mint.

### Root Cause

https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/sdai/src/SNst.sol#L357-L360
https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/sdai/src/SNst.sol#L371-L374
No slippage protection for function `deposit` and `mint`.

### Impact

When depositing, users are unable to obtain the expected share.
When minting, users pay more assets than expected.
Due to the lack of slippage protection, this could cause users to lose more than 1% of their assets.

### Mitigation

Add the slippage protection.

**Comment by sunbreak1211** [comment]
This issue doesn't make any sense, this contract is prepared to deposit an X amount of NST and later be able to withdraw >= X amount (excepting edge cases where a rounding down and a lack of nsr > RAY could provoke to be able to withdraw slightly less).
So this is not a swap function or similar where you want to put boundaries as you could get caught in a bad trade.
