### ISSUE TITLE
zraxx - A malicious urn owner can steal all funds.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-makerdao-endgame-judging#81]
zraxx

High

# A malicious urn owner can steal all funds.

### Summary

A malicious urn owner can steal all funds by calling function `free`.

### Root Cause

https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/lockstake/src/LockstakeEngine.sol#L238-L246
https://github.com/sherlock-audit/2024-06-makerdao-endgame/blob/main/lockstake/src/LockstakeEngine.sol#L340-L344
In `LockstakeEngine.sol`, anyone can open a urn contract. Users may stake into this contract due to a seemingly profit. However, a malicious urn owner may steal all users' funds at any time through the function `free`.

### Attack Path

1. The attacker open a urn contract, and set a good benfit to attract users to stake ( by function `lock`).
2. Users stake into this contract.
3. The attacker calls function `free` to steal all funds.

### Impact

Users' funds will be stolen.

### Mitigation

Need to ensure that the urn owner is trustworthy.

**Comment by telome** [comment]
Not an issue. Collateral can obviously only be withdrawn if it's been previously deposited to a user's own urn.
